### ISSUE TITLE
Bug in generation of pickled metrics

### ISSUE THREAD

**Issue by hellais** [TylerJFisher/ooni-lyzer#4]
I have figured out why it is that your pickles end up being so small. It is due to a bug present at this line: https://github.com/TylerJFisher/ooni-lyzer/blob/master/run.py#L77.

Basically since you are not making a copy of the header object you end up placing inside of the metrics list multiple copies of the same object and at every iteration of the loop you override the test_keys attribute of the same object instance.

What this leads to is an array of entries that are all the same and contain the value of the last item inserted inside of the list.

If you change that line with something like:

```
metrics = copy.deepcopy(header)
```

you will end up with a pointer to a new object and hence you will be adding new entries and you can then see that the sizes will actually be larger than their YAML equivalents.

**Comment by TylerJFisher** [comment]
Hi Arturo,
That's strange - did you run this locally in order to verify this behaviour?  

Based on my understanding, we're able to use a simple object reference to set the initial content of the metric dict since the header is the same for each entry in a given YAML file. 

By the way, the test_keys dict isn't actually inside of the header - it's found within the test dict as you can see here.

```python
...
        # The header is the same for all tests
        header, tests = self.__split_yml(target)
        metrics = []
        for test in tests:
            metric = header
            metric['report_filename'] = target.path
            metric['test_keys'] = test
            metrics.append(metric)
...
```

The content of the header dict looks like this at a given iteration:

```python
{'backend_version': '1.1.4',
 'input_hashes': [],
 'options': [],
 'probe_asn': 'AS12322',
 'probe_cc': 'FR',
 'probe_city': None,
 'probe_ip': '127.0.0.1',
 'report_id': 'dQycS2Sh7xbo0ZFeuzhBenpa6CwDYzO462tidRUQBL76SfMwJBNrdlYJDwu9Ozey',
 'software_name': 'ooniprobe',
 'software_version': '1.3.1',
 'start_time': 1451540240.0,
 'test_helpers': {'backend': '213.138.109.232'},
 'test_name': 'http_invalid_request_line',
 'test_version': '0.2'}
```

The content of the test_keys dict looks like this at a given iteration:

```python
{'input': None,
 'received': ['4M2P / HTTP/1.1\n\r',
              'GET / HTTP/8zC\n\r',
              '96oMf 45rxH 7OBDl iBBwN\n\r',
              'I AM A BODY'
              '/ HTTP/1.1\n'
              '\r'],
 'sent': ['4M2P / HTTP/1.1\n\r',
          'GET / HTTP/8zC\n\r',
          '96oMf 45rxH 7OBDl iBBwN\n\r',
          'I AM A BODY'
          '/ HTTP/1.1\n'
          '\r'],
 'tampering': False,
 'test_runtime': 7.7211010456085205,
 'test_start_time': 1451541175.0}
```

**Comment by hellais** [comment]
Yes I did run this locally to confirm this behaviour. You can see this for yourself if you just inspect one of the pickle files an realise that all the metrics are identical.

The problem lies in the fact that you are not copying the header dict, but just creating a pointer to it by assigning it to the local variable metrics. This simple python snippet should illustrate the problem perhaps a bit more clearly:

```
>>> somedict = {"a": "one", "b": "two"}
>>> somelist = []
>>> not_a_copy = somedict
>>> not_a_copy['key'] = 'value'
>>> somelist.append(not_a_copy)
>>> not_another_copy = somedict
>>> print somelist
[{'a': 'one', 'b': 'two', 'key': 'value'}]
>>> not_another_copy['key'] = 'value2'
>>> somelist.append(not_another_copy)
>>> print somelist
[{'a': 'one', 'b': 'two', 'key': 'value2'}, {'a': 'one', 'b': 'two', 'key': 'value2'}]
```

**Comment by TylerJFisher** [comment]
Alright - thanks for looking into this. I'll submit a patchset to correct this behaviour shortly.
